### ISSUE TITLE
Error: Backend not found: netlify-api

### ISSUE THREAD

**Issue by olliekav** [netlify/netlify-git-api#8]
I'm trying to get this running using Middleman but I keep getting the error above.

I've tried both `netlify-api` & `netlify_api` with no joy. Any ideas? My config.yml is set up as...

```
backend:
  name: netlify-api
  url: localhost:8080

production:
  backend:
    name: github
    repo: thisiscapra/thisiscapra.com
    branch: master

publish_mode: editorial_workflow
media_folder: "source/images/uploads"
public_folder: "source"

collections:
...
```
